version: '3.7'
services:
  service-config:
    build:
      context: ./
      dockerfile: ./cmd/service-config/Dockerfile
    restart: always
    networks:
      - service_epersediaan_epersediaan
  service-auth:
    build:
      context: ./
      dockerfile: ./cmd/service-auth/Dockerfile
    restart: always
    depends_on:
      - service-config
    networks:
      - simada_default
      - service_epersediaan_epersediaan
  service-report:
    build:
      context: ./
      dockerfile: ./cmd/service-report/Dockerfile
    restart: always
    depends_on:
      - service-config
    volumes:
       - ./storage:/storage
    networks:
      - simada_default
      - service_epersediaan_epersediaan
  service-worker:
    build:
      context: ./
      dockerfile: ./cmd/service-worker/Dockerfile
    restart: always
    depends_on:
      - service-config
    volumes:
      - ./storage:/storage
    networks:
      - simada_default
      - service_epersediaan_epersediaan
  service-transaction:
    build:
      context: ./
      dockerfile: ./cmd/service-transaction/Dockerfile
    restart: always
    volumes:
      - ./storage:/storage
    depends_on:
      - service-config
    networks:
      - simada_default
      - service_epersediaan_epersediaan
  service-pipeline:
    build:
      context: ./
      dockerfile: ./cmd/service-pipeline/Dockerfile
    restart: always
    volumes:
      - ./storage:/app/storage
    depends_on:
      - service-config
    networks:
      - simada_default
      - service_epersediaan_epersediaan
  service-elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    restart: always

networks:
  simada_default:
    external: true
  service_epersediaan_epersediaan:
    external: true